package view;

import javax.swing.*;
import java.awt.*;

public class MainFrame extends javax.swing.JFrame {

    private CardLayout cardLayout;
    private JPanel mainPanel;
    private JPanel topPanel;
    private JButton btnBack;
    private JLabel lblBrand;

    public MainFrame() {
        initComponents();
        setSize(1000, 700); // Slightly larger for better branding space
        setLocationRelativeTo(null); // Center window

        // --- TOP PANEL (BRANDING & NAVIGATION) ---
        topPanel = new JPanel(new BorderLayout());
        topPanel.setBackground(new Color(245, 245, 245)); // Light gray background
        topPanel.setBorder(BorderFactory.createEmptyBorder(10, 20, 10, 20));

        // 1. BRANDING (Left with Logo)
        JPanel brandPanel = new JPanel(new FlowLayout(FlowLayout.LEFT, 15, 0));
        brandPanel.setOpaque(false);

        // Load Logo (Assuming file is in user's home or resources - for now using
        // placeholder logic if file missing)
        ImageIcon logoIcon = null;
        try {
            // NOTE: In a real app, use getClass().getResource().
            // Here using absolute path generated by the agent or a robust fallback.
            // I will use a placeholder icon logic or try to load the generated one if path
            // is known.
            // For code stability, I'll use a simple colored Text/Icon approach if image
            // fails, but try to use the artifact path.
            String logoPath = "C:/Users/raiha/.gemini/antigravity/brain/bfaa8c5c-4332-4a38-b41c-6c1500c5bbc8/bimbelist_logo_icon_1767791627438.png";
            ImageIcon original = new ImageIcon(logoPath);
            if (original.getIconWidth() > 0) {
                Image img = original.getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH);
                logoIcon = new ImageIcon(img);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        JLabel lblLogo = new JLabel(logoIcon);
        JLabel lblAppName = new JLabel("Bimbelist");
        lblAppName.setFont(new Font("SansSerif", Font.BOLD, 22));
        lblAppName.setForeground(new Color(50, 50, 50));

        brandPanel.add(lblLogo);
        brandPanel.add(lblAppName);

        // 2. NAVIGATION (Right - Back Button)
        btnBack = new JButton("<< Kembali ke Menu");
        btnBack.setFont(new Font("SansSerif", Font.BOLD, 14));
        btnBack.setForeground(Color.WHITE);
        btnBack.setBackground(new Color(220, 53, 69)); // Reddish
        btnBack.setFocusPainted(false);
        btnBack.setBorderPainted(false);
        btnBack.setOpaque(true);
        btnBack.setPreferredSize(new Dimension(180, 40));
        btnBack.addActionListener(e -> showView("Home"));

        // Add Branding and Nav to Top Panel
        topPanel.add(brandPanel, BorderLayout.WEST);
        JPanel navPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT)); // Wrapper for right alignment
        navPanel.setOpaque(false);
        navPanel.add(btnBack);
        topPanel.add(navPanel, BorderLayout.EAST);

        // --- MAIN PANEL (CARDS) ---
        cardLayout = new CardLayout();
        mainPanel = new JPanel(cardLayout);

        // Add Panels
        mainPanel.add(new view.panels.HomePanel(name -> showView(name)), "Home");
        mainPanel.add(new view.panels.PengajarPanel(), "Pengajar");
        mainPanel.add(new view.panels.JadwalPanel(), "Jadwal");
        mainPanel.add(new view.panels.SiswaPanel(), "Siswa");

        // --- FRAME LAYOUT ---
        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(topPanel, BorderLayout.NORTH);
        getContentPane().add(mainPanel, BorderLayout.CENTER);

        // Initial State
        showView("Home");
    }

    public void showView(String name) {
        cardLayout.show(mainPanel, name);
        // On Home: Hide Back Button.
        // On Others: Show Back Button.
        btnBack.setVisible(!name.equals("Home"));

        // Optional: Update Title
        if (name.equals("Home")) {
            setTitle("Sistem Manajemen Jadwal Bimbel - Home");
        } else {
            setTitle("Sistem Manajemen Jadwal Bimbel - " + name);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Manajemen Sekolah - Triple T");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
